export { default as Beaker } from './Beaker';
export { default as Code } from './Code';
export { default as GitHub } from './Github';
export { default as NewFile } from './NewFile';
export { default as NewFolder } from './NewFolder';
export { default as Plus } from './Plus';
export { default as Setting } from './Setting';
export { default as Telegram } from './Telegram';
export { default as Test } from './Test';
